# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bul_content', models.TextField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bul_size', models.IntegerField()),
                ('if_shown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.TextField(max_length=20)),
                ('color_value', models.TextField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bul',
            name='bul_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bs.Color'),
        ),
    ]
